using Addons.Addons;
using Core.Client.Interfaces;
using Games.Games;
using Moq;
using Ports.Ports;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="ZHRecomp" /> port.
/// </summary>
public sealed class ZeroHourCmdArgumentsTests
{
    /// <summary>
    ///     Duke Nukem 3D game instance.
    /// </summary>
    private readonly DukeGame _dukeGame;

    /// <summary>
    ///     Duke Zero Hour campaign.
    /// </summary>
    private readonly DukeCampaign _dukeZhCamp;

    /// <summary>
    ///     Initializes a new instance of the <see cref="ZeroHourCmdArgumentsTests" /> class.
    /// </summary>
    public ZeroHourCmdArgumentsTests()
    {
        (_dukeGame, _, _, _, _, _, _dukeZhCamp, _, _, _, _) = PortTestSetups.Duke3D();
    }

    /// <summary>
    ///     Tests that ZHRecomp generates correct start arguments for Duke Zero Hour.
    /// </summary>
    [Fact]
    public void DukeTest()
    {
        Mock<IConfigProvider> _config = new();
        ZHRecomp redNukem = new(_config.Object);

        var args = redNukem.GetStartGameArgs(_dukeGame, _dukeZhCamp, [], [], true, true);

        Assert.Equal(string.Empty, args);
    }
}
