using Addons.Addons;
using Core.All.Enums;
using Core.All.Enums.Addons;
using Core.Client.Helpers;
using Games.Games;
using Ports.Ports.EDuke32;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="EDuke32" /> port.
/// </summary>
public sealed class EDuke32CmdArgumentsTests
{
    private readonly DukeCampaign _dukeCamp;
    private readonly DukeCampaign _dukeDcCamp;
    private readonly DukeGame _dukeGame;
    private readonly LooseMap _dukeLooseMap;
    private readonly AutoloadModsTestSetups _dukeMods;
    private readonly DukeCampaign _dukeNwCamp;
    private readonly DukeCampaign _dukeTcForVaca;
    private readonly DukeCampaign _dukeVaca;
    private readonly DukeCampaign _dukeWtCamp;
    private readonly DukeCampaign _namCamp;

    private readonly NamGame _namGame;
    private readonly AutoloadModsTestSetups _namMods;
    private readonly DukeCampaign _ww2Camp;

    private readonly WW2GIGame _ww2Game;
    private readonly AutoloadModsTestSetups _ww2Mods;
    private readonly DukeCampaign _ww2PlatoonCamp;
    private readonly DukeCampaign _furyCamp;

    private readonly FuryGame _furyGame;
    private readonly AutoloadModsTestSetups _furyMods;

    /// <summary>
    ///     Initializes a new instance of the <see cref="EDuke32CmdArgumentsTests" /> class.
    /// </summary>
    public EDuke32CmdArgumentsTests()
    {
        (_dukeGame, _dukeCamp, _dukeVaca, _dukeTcForVaca, _dukeWtCamp, _, _, _dukeDcCamp, _dukeNwCamp, _dukeLooseMap, _dukeMods) = PortTestSetups.Duke3D();
        (_namGame, _namCamp, _namMods) = PortTestSetups.Nam();
        (_ww2Game, _ww2Camp, _ww2PlatoonCamp, _ww2Mods) = PortTestSetups.WW2GI();
        (_furyGame, _furyCamp, _furyMods) = PortTestSetups.Fury();
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for the Duke base game with standard mods.
    /// </summary>
    [Fact]
    public void DukeTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeCamp, mods, [], true, true, 3);

        var expected = "" +
                       " -g \"enabled_mod.zip\"" +
                       " -mh \"ENABLED1.DEF\"" +
                       " -mh \"ENABLED2.DEF\"" +
                       " -mx \"ENABLED1.CON\"" +
                       " -mx \"ENABLED2.CON\"" +
                       " -g \"mod_incompatible_with_addon.zip\"" +
                       " -g \"incompatible_mod_with_compatible_version.zip\"" +
                       " -g \"dependent_mod.zip\"" +
                       " -g \"dependent_mod_with_compatible_version.zip\"" +
                       " -g \"feature_mod.zip\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       " -j \"D:\\Games\\Duke3D\"" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -cachesize 262144" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for Duke World Tour.
    /// </summary>
    [Fact]
    public void DukeWtTest()
    {
        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeWtCamp, [], [], true, true);

        var expected = $"" +
                       $" -j \"D:\\Games\\DukeWT\"" +
                       $" -addon 0" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Ports\\EDuke32\\WTStopgap\"" +
                       $" -gamegrp e32wt.grp" +
                       $" -mh e32wt.def" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for Duke Caribbean with addon mods.
    /// </summary>
    [Fact]
    public void DukeVacaTest()
    {
        var mods = _dukeMods.AddonModsWithCons;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeVaca, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModRequiresAddon}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"D:\\Games\\Duke3D\\Vaca\"" +
                       $" -grp VACATION.GRP" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for Duke It Out In DC.
    /// </summary>
    [Fact]
    public void DukeDcTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeDcCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"D:\\Games\\Duke3D\\DC\"" +
                       $" -grp DUKEDC.GRP" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for Duke Nuclear Winter.
    /// </summary>
    [Fact]
    public void DukeNwTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeNwCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"D:\\Games\\Duke3D\\NW\"" +
                       $" -grp NWINTER.GRP" +
                       $" -x NWINTER.CON" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for a Duke TC.
    /// </summary>
    [Fact]
    public void DukeTCTest()
    {
        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeTcForVaca, [], [], true, true);

        var expected = $"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"D:\\Games\\Duke3D\\Vaca\"" +
                       $" -grp VACATION.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       $" -j \"{Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns")}\"" +
                       $" -g \"duke_tc.zip\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for a Duke TC in an unpacked folder.
    /// </summary>
    [Fact]
    public void DukeTCFolderTest()
    {
        EDuke32 eduke32 = new();

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns", "duke_tc_folder");

        var tcFolder = CampaignTestFactory.CreateDukeCampaign(
            "duke-tc-folder",
            GameEnum.Duke3D,
            new AddonFilePathWrapper(folderPath, "addon.json"),
            dependentAddons: new Dictionary<string, string?>
            {
                {
                    nameof(DukeAddonEnum.DukeVaca), null
                }
            },
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        var args = eduke32.GetStartGameArgs(_dukeGame, tcFolder, [], [], true, true);

        var expected = $"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"D:\\Games\\Duke3D\\Vaca\"" +
                       $" -grp VACATION.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       $" -game_dir \"{folderPath}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for a Duke TC with an executable override.
    /// </summary>
    [Fact]
    public void DukeTCExeOverrideTest()
    {
        EDuke32 eduke32 = new();

        var zipFilePath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns", "duke_tc.zip");

        var tcExe = CampaignTestFactory.CreateDukeCampaign(
            "duke-tc-exe",
            GameEnum.Duke3D,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            dependentAddons: new Dictionary<string, string?>
            {
                {
                    nameof(DukeAddonEnum.DukeVaca), null
                }
            },
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"],
            executables: new Dictionary<OSEnum, Dictionary<PortEnum, string>>
            {
                {
                    OSEnum.Windows, new Dictionary<PortEnum, string>
                    {
                        {
                            PortEnum.EDuke32, "eduke32.exe"
                        }
                    }
                }
            });

        var args = eduke32.GetStartGameArgs(_dukeGame, tcExe, [], [], true, true);

        var expected = $"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"D:\\Games\\Duke3D\\Vaca\"" +
                       $" -grp VACATION.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for a packed addon.
    /// </summary>
    [Fact]
    public void DukePackedAddonTest()
    {
        EDuke32 eduke32 = new();

        var packedCamp = PortTestSetups.PackedDukeAddonCampaign();
        var folderPath = packedCamp.FileInfo.Value.PathToFolder;
        var fileName = packedCamp.FileInfo.Value.FileName;

        var args = eduke32.GetStartGameArgs(_dukeGame, packedCamp, [], [], true, true);

        var expected = "" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{folderPath}\"" +
                       $" -g \"{fileName}\"" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -cachesize 262144" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for a Duke loose map with standard mods.
    /// </summary>
    [Fact]
    public void DukeLooseMapTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeLooseMap, mods, [], true, true, 3);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"D:\\Games\\Duke3D\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       $" -s3" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -cachesize 262144" +
                       $" -h \"a\""
            ;

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for NAM.
    /// </summary>
    [Fact]
    public void NamTest()
    {
        var mods = _namMods.MinimalMods;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_namGame, _namCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\NAM\\Mods\"" +
                       " -j \"D:\\Games\\NAM\"" +
                       " -nam" +
                       " -gamegrp NAM.GRP" +
                       " -x GAME.CON" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -cachesize 262144" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for World War II GI.
    /// </summary>
    [Fact]
    public void WW2GITest()
    {
        var mods = _ww2Mods.MinimalMods;

        EDuke32 eDuke = new();

        var args = eDuke.GetStartGameArgs(_ww2Game, _ww2Camp, mods, [], true, true);

        var expected = "" +
                       " -g \"enabled_mod.zip\"" +
                       " -mh \"ENABLED1.DEF\"" +
                       " -mh \"ENABLED2.DEF\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\WW2GI\\Mods\"" +
                       " -j \"D:\\Games\\WW2GI\"" +
                       " -ww2gi" +
                       " -gamegrp WW2GI.GRP" +
                       " -x GAME.CON" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -cachesize 262144" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for WW2GI Platoon.
    /// </summary>
    [Fact]
    public void WW2GIPlatoonTest()
    {
        var mods = _ww2Mods.MinimalMods;

        EDuke32 eDuke = new();

        var args = eDuke.GetStartGameArgs(_ww2Game, _ww2PlatoonCamp, mods, [], true, true);

        var expected = "" +
                       " -g \"enabled_mod.zip\"" +
                       " -mh \"ENABLED1.DEF\"" +
                       " -mh \"ENABLED2.DEF\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\WW2GI\\Mods\"" +
                       " -j \"D:\\Games\\WW2GI\"" +
                       " -ww2gi" +
                       " -gamegrp WW2GI.GRP" +
                       " -grp PLATOONL.DAT" +
                       " -x PLATOONL.DEF" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -cachesize 262144" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for Ion Fury.
    /// </summary>
    [Fact]
    public void FuryTest()
    {
        var mods = _furyMods.StandardModsWithCons;

        EDuke32 eduke32 = new();

        var args = eduke32.GetStartGameArgs(_furyGame, _furyCamp, mods, [], true, true, 3);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Fury\\Mods\"" +
                       $" -j \"D:\\Games\\Fury\"" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       $" -usecwd" +
                       " -cachesize 262144" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests the EDuke32 command-line arguments for a Fury TC.
    /// </summary>
    [Fact]
    public void FuryTCTest()
    {
        EDuke32 eduke32 = new();

        var zipFilePath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Fury", "Campaigns", "fury_tc.zip");
        var folderPath = Path.GetDirectoryName(zipFilePath);
        var fileName = Path.GetFileName(zipFilePath);

        var tcCamp = new DukeCampaign
        {
            AddonId = new("fury-tc", "1.0"),
            Type = AddonTypeEnum.TC,
            Title = "Fury TC",
            SupportedGame = new(GameEnum.Fury),
            FileInfo = new AddonFilePathWrapper(zipFilePath, "addon.json"),
            DependentAddons = null,
            IncompatibleAddons = null,
            GridImageHash = null,
            PreviewImageHash = null,
            Description = null,
            Author = null,
            ReleaseDate = null,
            MainCon = null,
            AdditionalCons = null,
            MainDef = null,
            AdditionalDefs = null,
            RTS = null,
            StartMap = null,
            RequiredFeatures = null,
            Executables = null,
            Options = null
        };

        var args = eduke32.GetStartGameArgs(_furyGame, tcCamp, [], [], true, true);

        var expected = "" +
                       $" -j \"D:\\Games\\Fury\"" +
                       $" -j \"{folderPath}\"" +
                       $" -g \"{fileName}\"" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -cachesize 262144" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that <see cref="EDuke32.BeforeStart" /> does not throw when FileInfo is null.
    /// </summary>
    [Fact]
    public void BeforeStart_NullFileInfo_DoesNotThrow()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(tempDir);

        try
        {
            var game = new DukeGame
            {
                Duke64RomPath = null,
                DukeZHRomPath = null,
                DukeWTInstallPath = null,
                GameInstallFolder = tempDir,
                AddonsPaths = []
            };

            var camp = new DukeCampaign
            {
                AddonId = new("test-camp", null),
                Type = AddonTypeEnum.Official,
                Title = "Test",
                SupportedGame = new(GameEnum.Duke3D, null, null),
                FileInfo = null,
                GridImageHash = null,
                PreviewImageHash = null,
                Description = null,
                Author = null,
                ReleaseDate = null,
                MainDef = null,
                AdditionalDefs = null,
                MainCon = null,
                AdditionalCons = null,
                RTS = null,
                StartMap = null,
                DependentAddons = null,
                IncompatibleAddons = null,
                RequiredFeatures = null,
                Executables = null,
                Options = null
            };

            EDuke32 eduke32 = new();
            eduke32.BeforeStart(game, camp);
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    /// <summary>
    ///     Tests that <see cref="EDuke32.BeforeStart" /> lazily creates the WTStopgap folder.
    /// </summary>
    [Fact]
    public void BeforeStart_CreatesWTStopgapFolder()
    {
        var stopgapFolder = Path.Combine(new EDuke32().InstallFolderPath, ClientConsts.WTStopgap);

        if (Directory.Exists(stopgapFolder))
        {
            Directory.Delete(stopgapFolder, true);
        }

        try
        {
            Assert.False(Directory.Exists(stopgapFolder));

            var game = new DukeGame
            {
                Duke64RomPath = null,
                DukeZHRomPath = null,
                DukeWTInstallPath = null,
                GameInstallFolder = Path.GetTempPath(),
                AddonsPaths = []
            };

            var camp = new DukeCampaign
            {
                AddonId = new("wt-test", null),
                Type = AddonTypeEnum.Official,
                Title = "WT Test",
                SupportedGame = new(GameEnum.Duke3D, null, null),
                FileInfo = null,
                GridImageHash = null,
                PreviewImageHash = null,
                Description = null,
                Author = null,
                ReleaseDate = null,
                MainDef = null,
                AdditionalDefs = null,
                MainCon = null,
                AdditionalCons = null,
                RTS = null,
                StartMap = null,
                DependentAddons = null,
                IncompatibleAddons = null,
                RequiredFeatures = null,
                Executables = null,
                Options = null
            };

            new EDuke32().BeforeStart(game, camp);

            Assert.True(Directory.Exists(stopgapFolder));
            Assert.True(Directory.GetFiles(stopgapFolder).Length > 0);
        }
        finally
        {
            if (Directory.Exists(stopgapFolder))
            {
                Directory.Delete(stopgapFolder, true);
            }
        }
    }
}
