using Addons.Addons;
using Core.Client.Config;
using Games.Games;
using Ports.Ports.EDuke32;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="Fury" /> port.
/// </summary>
public sealed class FuryCmdArgumentsTests
{
    /// <summary>
    ///     Fury campaign.
    /// </summary>
    private readonly DukeCampaign _camp;

    /// <summary>
    ///     Fury game instance.
    /// </summary>
    private readonly FuryGame _game;

    /// <summary>
    ///     Fury mods test setups.
    /// </summary>
    private readonly AutoloadModsTestSetups _mods;

    /// <summary>
    ///     Initializes a new instance of the <see cref="FuryCmdArgumentsTests" /> class.
    /// </summary>
    public FuryCmdArgumentsTests()
    {
        (_game, _camp, _mods) = PortTestSetups.Fury();
    }

    /// <summary>
    ///     Tests the Fury port command-line arguments with standard mods.
    /// </summary>
    [Fact]
    public void FuryTest()
    {
        var mods = _mods.StandardModsWithCons;

        Fury fury = new(new ConfigProviderFake());

        var args = fury.GetStartGameArgs(_game, _camp, mods, [], true, true, 3);

        var expected = $"" +
                       $" -g \"enabled_mod.zip\"" +
                       $" -mh \"ENABLED1.DEF\"" +
                       $" -mh \"ENABLED2.DEF\"" +
                       $" -mx \"ENABLED1.CON\"" +
                       $" -mx \"ENABLED2.CON\"" +
                       $" -g \"mod_incompatible_with_addon.zip\"" +
                       $" -g \"incompatible_mod_with_compatible_version.zip\"" +
                       $" -g \"dependent_mod.zip\"" +
                       $" -g \"dependent_mod_with_compatible_version.zip\"" +
                       $" -g \"feature_mod.zip\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Fury\\Mods\"" +
                       $" -s3" +
                       $" -quick" +
                       $" -nosetup" +
                       $"";

        NormalizerHelper.NormalizeExpectedArgs(ref args, ref expected);

        Assert.Equal(expected, args);
    }
}
