using Addons.Addons;
using Core.All.Enums;
using Games.Games;
using Ports.Ports.EDuke32;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="NotBlood" /> port.
/// </summary>
public sealed class NotBloodCmdArgumentsTests
{
    private readonly BloodCampaign _bloodCamp;
    private readonly BloodCampaign _bloodCampWithOptions;
    private readonly BloodCampaign _bloodCpCamp;
    private readonly BloodGame _bloodGame;
    private readonly LooseMap _bloodLooseMap;
    private readonly AutoloadModsTestSetups _bloodMods;
    private readonly BloodCampaign _bloodTc;
    private readonly BloodCampaign _bloodTcExeOverride;
    private readonly BloodCampaign _bloodTcFolder;
    private readonly BloodCampaign _bloodTcIncompatibleWithEnabledMod;
    private readonly BloodCampaign _bloodTcIncompatibleWithEverything;

    /// <summary>
    ///     Initializes a new instance of the <see cref="NotBloodCmdArgumentsTests" /> class.
    /// </summary>
    public NotBloodCmdArgumentsTests()
    {
        (_bloodGame, _bloodCamp, _bloodCampWithOptions, _bloodCpCamp, _bloodTc, _bloodTcFolder, _bloodTcExeOverride, _bloodTcIncompatibleWithEnabledMod, _bloodTcIncompatibleWithEverything, _bloodLooseMap, _bloodMods) = PortTestSetups.Blood();
    }

    /// <summary>
    ///     Tests that NotBlood generates correct start arguments for a standard campaign.
    /// </summary>
    [Fact]
    public void BloodTest()
    {
        var mods = _bloodMods.StandardMods;

        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodCamp, mods, [], true, true, 2);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Blood\\Mods\"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"BLOOD.INI\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood generates correct start arguments for a campaign with an INI file.
    /// </summary>
    [Fact]
    public void BloodCPTest()
    {
        var mods = _bloodMods.StandardMods;

        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodCpCamp, mods, [], true, true, 2);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -g \"{CmdArgsTestData.ModRequiresAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Blood\\Mods\"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"CRYPTIC.INI\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood generates correct start arguments for a total conversion.
    /// </summary>
    [Fact]
    public void BloodTCTest()
    {
        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodTc, [], [], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"TC.INI\"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -g \"blood_tc.zip\"" +
                       " -rff \"TC.RFF\"" +
                       " -snd \"TC.SND\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood generates correct start arguments for a TC folder.
    /// </summary>
    [Fact]
    public void BloodTCFolderTest()
    {
        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodTcFolder, [], [], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"TC.INI\"" +
                       " -game_dir \"D:\\Games\\Blood\\blood_tc_folder\"" +
                       " -rff \"TC.RFF\"" +
                       " -snd \"TC.SND\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood handles an executable override correctly.
    /// </summary>
    [Fact]
    public void BloodTcExeOverride()
    {
        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodTcExeOverride, [], [], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"TC.INI\"" +
                       " -rff \"TC.RFF\"" +
                       " -snd \"TC.SND\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood handles an addon incompatible with an enabled mod.
    /// </summary>
    [Fact]
    public void BloodIncompatibleWithEnabledModTest()
    {
        var mods = _bloodMods.Enabled;

        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodTcIncompatibleWithEnabledMod, mods, [], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"TC.INI\"" +
                       " -game_dir \"D:\\Games\\Blood\\blood_tc_folder\"" +
                       " -rff \"TC.RFF\"" +
                       " -snd \"TC.SND\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood handles an addon incompatible with everything.
    /// </summary>
    [Fact]
    public void BloodIncompatibleWithEverythingTest()
    {
        var mods = _bloodMods.StandardMods;

        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodTcIncompatibleWithEverything, mods, [], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"TC.INI\"" +
                       " -game_dir \"D:\\Games\\Blood\\blood_tc_folder\"" +
                       " -rff \"TC.RFF\"" +
                       " -snd \"TC.SND\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood generates correct start arguments for a loose map.
    /// </summary>
    [Fact]
    public void BloodLooseMapTest()
    {
        var mods = _bloodMods.StandardMods;

        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodLooseMap, mods, [], true, true, 2);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Blood\\Mods\"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"BLOOD.INI\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Blood\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood generates correct start arguments with enabled options.
    /// </summary>
    [Fact]
    public void BloodWithOptionsTest()
    {
        NotBlood notblood = new();

        var args = notblood.GetStartGameArgs(_bloodGame, _bloodCampWithOptions, [], ["option 2"], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -mh \"OPT2.DEF\"" +
                       " -mh \"OPT2_2.DEF\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that NotBlood does not throw when the addon file info is null.
    /// </summary>
    [Fact]
    public void Blood_NullFileInfo_DoesNotThrow()
    {
        NotBlood notblood = new();

        var bloodTcNull = new BloodCampaign
        {
            AddonId = new("blood-tc-null", "1.0"),
            Type = AddonTypeEnum.TC,
            Title = "Blood TC",
            SupportedGame = new(GameEnum.Blood),
            FileInfo = null,
            GridImageHash = null,
            PreviewImageHash = null,
            Description = null,
            Author = null,
            ReleaseDate = null,
            MainDef = null,
            AdditionalDefs = null,
            INI = "TC.INI",
            RFF = "TC.RFF",
            SND = "TC.SND",
            StartMap = null,
            DependentAddons = null,
            IncompatibleAddons = null,
            RequiredFeatures = null,
            Executables = null,
            Options = null
        };

        var args = notblood.GetStartGameArgs(_bloodGame, bloodTcNull, [], [], true, true, 2);

        var expected = $"" +
                       " -j \"D:\\Games\\Blood\"" +
                       " -ini \"TC.INI\"" +
                       " -s 2" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }
}
