using Addons.Addons;
using Games.Games;
using Ports.Ports.EDuke32;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="PCExhumed" /> port.
/// </summary>
public sealed class PCExhumedCmdArgumentsTests
{
    /// <summary>
    ///     Slave (Exhumed) campaign.
    /// </summary>
    private readonly GenericCampaign _slaveCamp;

    /// <summary>
    ///     Slave game instance.
    /// </summary>
    private readonly SlaveGame _slaveGame;

    /// <summary>
    ///     Slave mods test setups.
    /// </summary>
    private readonly AutoloadModsTestSetups _slaveMods;

    /// <summary>
    ///     Initializes a new instance of the <see cref="PCExhumedCmdArgumentsTests" /> class.
    /// </summary>
    public PCExhumedCmdArgumentsTests()
    {
        (_slaveGame, _slaveCamp, _slaveMods) = PortTestSetups.Slave();
    }

    /// <summary>
    ///     Tests that PCExhumed generates correct start arguments for a Slave campaign.
    /// </summary>
    [Fact]
    public void SlaveTest()
    {
        var mods = _slaveMods.MinimalMods;

        PCExhumed pcExhumed = new();

        var args = pcExhumed.GetStartGameArgs(_slaveGame, _slaveCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"enabled_mod.zip\"" +
                       $" -mh \"ENABLED1.DEF\"" +
                       $" -mh \"ENABLED2.DEF\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Slave\\Mods\"" +
                       $" -usecwd" +
                       $" -j \"D:\\Games\\Slave\"" +
                       $" -h \"a\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $"";

        NormalizerHelper.NormalizeExpectedArgs(ref args, ref expected);

        Assert.Equal(expected, args);
    }
}
