using Addons.Addons;
using Core.All.Enums;
using Core.All.Enums.Addons;
using Core.Client.Helpers;
using Games.Games;
using Ports.Ports;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="Raze" /> port.
/// </summary>
public sealed class RazeCmdArgumentsTests
{
    private readonly BloodCampaign _bloodCamp;
    private readonly BloodCampaign _bloodCpCamp;
    private readonly BloodGame _bloodGame;
    private readonly LooseMap _bloodLooseMap;
    private readonly AutoloadModsTestSetups _bloodMods;
    private readonly BloodCampaign _bloodTc;
    private readonly BloodCampaign _bloodTcExeOverride;
    private readonly BloodCampaign _bloodTcFolder;
    private readonly DukeCampaign _dukeCamp;

    private readonly DukeGame _dukeGame;
    private readonly LooseMap _dukeLooseMap;
    private readonly AutoloadModsTestSetups _dukeMods;
    private readonly DukeCampaign _dukeTcForVaca;
    private readonly DukeCampaign _dukeVaca;
    private readonly DukeCampaign _dukeWtCamp;
    private readonly DukeCampaign _namCamp;

    private readonly NamGame _namGame;
    private readonly AutoloadModsTestSetups _namMods;
    private readonly DukeCampaign _redneckAgainCamp;
    private readonly DukeCampaign _redneckCamp;

    private readonly RedneckGame _redneckGame;
    private readonly AutoloadModsTestSetups _redneckMods;
    private readonly GenericCampaign _slaveCamp;

    private readonly SlaveGame _slaveGame;
    private readonly AutoloadModsTestSetups _slaveMods;
    private readonly GenericCampaign _wangCamp;

    private readonly WangGame _wangGame;
    private readonly LooseMap _wangLooseMap;
    private readonly AutoloadModsTestSetups _wangMods;
    private readonly GenericCampaign _wangTdCamp;
    private readonly DukeCampaign _ww2Camp;

    private readonly WW2GIGame _ww2Game;
    private readonly AutoloadModsTestSetups _ww2Mods;
    private readonly DukeCampaign _ww2PlatoonCamp;

    /// <summary>
    ///     Initializes a new instance of the <see cref="RazeCmdArgumentsTests" /> class.
    /// </summary>
    public RazeCmdArgumentsTests()
    {
        (_bloodGame, _bloodCamp, _, _bloodCpCamp, _bloodTc, _bloodTcFolder, _bloodTcExeOverride, _, _, _bloodLooseMap, _bloodMods) = PortTestSetups.Blood();
        (_dukeGame, _dukeCamp, _dukeVaca, _dukeTcForVaca, _dukeWtCamp, _, _, _, _, _dukeLooseMap, _dukeMods) = PortTestSetups.Duke3D();
        (_namGame, _namCamp, _namMods) = PortTestSetups.Nam();
        (_redneckGame, _redneckCamp, _redneckAgainCamp, _, _redneckMods) = PortTestSetups.Redneck();
        (_slaveGame, _slaveCamp, _slaveMods) = PortTestSetups.Slave();
        (_wangGame, _wangCamp, _wangTdCamp, _wangLooseMap, _wangMods) = PortTestSetups.Wang();
        (_ww2Game, _ww2Camp, _ww2PlatoonCamp, _ww2Mods) = PortTestSetups.WW2GI();
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Blood.
    /// </summary>
    [Fact]
    public void BloodTest()
    {
        var mods = _bloodMods.StandardMods;

        Raze raze = new();

        raze.BeforeStart(_bloodGame, _bloodCamp);
        var args = raze.GetStartGameArgs(_bloodGame, _bloodCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -file \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       " -ini \"BLOOD.INI\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Blood\\blood\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Blood"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Blood/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Blood CP campaign.
    /// </summary>
    [Fact]
    public void BloodCPTest()
    {
        var mods = _bloodMods.StandardMods;

        Raze raze = new();

        raze.BeforeStart(_bloodGame, _bloodCamp);
        var args = raze.GetStartGameArgs(_bloodGame, _bloodCpCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -file \"{CmdArgsTestData.ModRequiresAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       " -ini \"CRYPTIC.INI\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Blood\\bloodcp\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Blood"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Blood/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Blood total conversion.
    /// </summary>
    [Fact]
    public void BloodTCTest()
    {
        Raze raze = new();

        raze.BeforeStart(_bloodGame, _bloodTc);
        var args = raze.GetStartGameArgs(_bloodGame, _bloodTc, [], [], true, true);

        var expected = $"" +
                       " -ini \"TC.INI\"" +
                       " -file \"blood_tc.zip\"" +
                       " -file \"TC.RFF\"" +
                       " -file \"TC.SND\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Blood\\blood-tc\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Blood"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Blood/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Blood TC folder.
    /// </summary>
    [Fact]
    public void BloodTCFolderTest()
    {
        Raze raze = new();

        raze.BeforeStart(_bloodGame, _bloodTcFolder);
        var args = raze.GetStartGameArgs(_bloodGame, _bloodTcFolder, [], [], true, true);

        var expected = $"" +
                       " -ini \"TC.INI\"" +
                       " -file \"D:\\Games\\Blood\\blood_tc_folder\"" +
                       " -file \"TC.RFF\"" +
                       " -file \"TC.SND\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Blood\\blood-tc-folder\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Blood"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Blood/Mods", "D:/Games/Blood/blood_tc_folder"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Blood TC with an executable override.
    /// </summary>
    [Fact]
    public void BloodTCExeOverrideTest()
    {
        Raze raze = new();

        raze.BeforeStart(_bloodGame, _bloodTcExeOverride);
        var args = raze.GetStartGameArgs(_bloodGame, _bloodTcExeOverride, [], [], true, true);

        var expected = $"" +
                       " -ini \"TC.INI\"" +
                       " -file \"TC.RFF\"" +
                       " -file \"TC.SND\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Blood\\blood-tc-exe-override\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Blood"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Blood/Mods", "D:/Games/Blood/blood_tc_folder"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Blood loose map.
    /// </summary>
    [Fact]
    public void BloodLooseMapTest()
    {
        var mods = _bloodMods.StandardMods;

        Raze raze = new();

        raze.BeforeStart(_bloodGame, _bloodLooseMap);
        var args = raze.GetStartGameArgs(_bloodGame, _bloodLooseMap, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -file \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       " -ini \"BLOOD.INI\"" +
                       $" -file \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Blood\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Blood\\loose-map\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Blood"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Blood/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Duke Nukem 3D.
    /// </summary>
    [Fact]
    public void DukeTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        Raze raze = new();

        raze.BeforeStart(_dukeGame, _dukeCamp);
        var args = raze.GetStartGameArgs(_dukeGame, _dukeCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -addcon \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -file \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -addon 0" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\duke3d\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(RazeDukePaths(), [$"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Duke World Tour.
    /// </summary>
    [Fact]
    public void DukeWtTest()
    {
        Raze raze = new();

        raze.BeforeStart(_dukeGame, _dukeWtCamp);
        var args = raze.GetStartGameArgs(_dukeGame, _dukeWtCamp, [], [], true, true);

        var expected = $"" +
                       $" -addon 0" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\duke3d_wt\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/DukeWT"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Duke Caribbean (Vacation).
    /// </summary>
    [Fact]
    public void DukeVacaTest()
    {
        var mods = _dukeMods.AddonModsWithCons;

        Raze raze = new();

        raze.BeforeStart(_dukeGame, _dukeVaca);
        var args = raze.GetStartGameArgs(_dukeGame, _dukeVaca, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -addcon \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -file \"{CmdArgsTestData.ModRequiresAddon}\"" +
                       $" -addon 3" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\dukevaca\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(RazeDukePaths(), [$"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Duke total conversion.
    /// </summary>
    [Fact]
    public void DukeTCTest()
    {
        Raze raze = new();

        raze.BeforeStart(_dukeGame, _dukeTcForVaca);
        var args = raze.GetStartGameArgs(_dukeGame, _dukeTcForVaca, [], [], true, true);

        var expected = $"" +
                       $" -addon 3" +
                       $" -con \"{CmdArgsTestData.TcCon}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon2}\"" +
                       $" -file \"duke_tc.zip\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\duke-tc\"" +
                       $" -def \"{CmdArgsTestData.TcDef}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(
            RazeDukePaths(), [
                $"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods",
                $"{Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns")}"
            ]
            );
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Duke TC in an unpacked folder.
    /// </summary>
    [Fact]
    public void DukeTCFolderTest()
    {
        Raze raze = new();

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns", "duke_tc_folder");

        var dukeTcFolder = CampaignTestFactory.CreateDukeCampaign(
            "duke-tc-folder",
            GameEnum.Duke3D,
            new AddonFilePathWrapper(folderPath, "addon.json"),
            dependentAddons: new Dictionary<string, string?>
            {
                {
                    nameof(DukeAddonEnum.DukeVaca), null
                }
            },
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        raze.BeforeStart(_dukeGame, dukeTcFolder);
        var args = raze.GetStartGameArgs(_dukeGame, dukeTcFolder, [], [], true, true);

        var expected = $"" +
                       $" -addon 3" +
                       $" -con \"{CmdArgsTestData.TcCon}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon2}\"" +
                       $" -file \"{folderPath}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\duke-tc-folder\"" +
                       $" -def \"{CmdArgsTestData.TcDef}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(RazeDukePaths(), [$"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a packed addon.
    /// </summary>
    [Fact]
    public void DukePackedAddonTest()
    {
        Raze raze = new();

        var packedCamp = PortTestSetups.PackedDukeAddonCampaign();
        var folderPath = packedCamp.FileInfo.Value.PathToFolder;
        var fileName = packedCamp.FileInfo.Value.FileName;

        raze.BeforeStart(_dukeGame, packedCamp);
        var args = raze.GetStartGameArgs(_dukeGame, packedCamp, [], [], true, true);

        var expected = $"" +
                       $" -addon 0" +
                       $" -file \"{fileName}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\packed-camp\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(
            RazeDukePaths(), [
                $"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods",
                $"{folderPath}"
            ]
            );
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Duke loose map.
    /// </summary>
    [Fact]
    public void DukeLooseMapTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        var dukeGame = new DukeGame()
        {
            Duke64RomPath = null,
            DukeZHRomPath = null,
            DukeWTInstallPath = null,
            GameInstallFolder = Path.Combine("D:", "Games", "Duke3D")
        };

        Raze raze = new();

        raze.BeforeStart(dukeGame, _dukeLooseMap);
        var args = raze.GetStartGameArgs(dukeGame, _dukeLooseMap, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -addcon \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -file \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -file \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Duke3D\\loose-map\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Duke3D"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Duke3D/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for NAM.
    /// </summary>
    [Fact]
    public void NamTest()
    {
        var mods = _namMods.MinimalMods;

        Raze raze = new();

        raze.BeforeStart(_namGame, _namCamp);
        var args = raze.GetStartGameArgs(_namGame, _namCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -nam" +
                       $" -file NAM.GRP" +
                       $" -con GAME.CON" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\NAM\\nam\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/NAM"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/NAM/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a NAM total conversion.
    /// </summary>
    [Fact]
    public void NamTcTest()
    {
        Raze raze = new();

        var zipFilePath = Path.Combine("D:", "Games", "NAM", "nam_tc.zip");

        var namTc = CampaignTestFactory.CreateDukeCampaign(
            "nam-tc",
            GameEnum.NAM,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        raze.BeforeStart(_namGame, namTc);
        var args = raze.GetStartGameArgs(_namGame, namTc, [], [], true, true);

        var expected = $"" +
                       $" -nam" +
                       $" -file NAM.GRP" +
                       $" -con \"{CmdArgsTestData.TcCon}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon2}\"" +
                       $" -file \"nam_tc.zip\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\NAM\\nam-tc\"" +
                       $" -def \"{CmdArgsTestData.TcDef}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/NAM"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/NAM/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Redneck Rampage.
    /// </summary>
    [Fact]
    public void RedneckTest()
    {
        var mods = _redneckMods.MinimalMods;

        Raze raze = new();

        raze.BeforeStart(_redneckGame, _redneckCamp);
        var args = raze.GetStartGameArgs(_redneckGame, _redneckCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Redneck\\redneck\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Redneck"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Redneck/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Redneck Rampage Rides Again.
    /// </summary>
    [Fact]
    public void RedneckAgainTest()
    {
        var mods = _redneckMods.MinimalMods;

        Raze raze = new();

        raze.BeforeStart(_redneckGame, _redneckAgainCamp);
        var args = raze.GetStartGameArgs(_redneckGame, _redneckAgainCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Redneck\\ridesagain\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Again"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Redneck/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Redneck Rampage total conversion.
    /// </summary>
    [Fact]
    public void RedneckTcTest()
    {
        Raze raze = new();

        var zipFilePath = Path.Combine("D:", "Games", "Redneck", "redneck_tc.zip");

        var redneckTc = CampaignTestFactory.CreateDukeCampaign(
            "redneck-tc",
            GameEnum.Redneck,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        raze.BeforeStart(_redneckGame, redneckTc);
        var args = raze.GetStartGameArgs(_redneckGame, redneckTc, [], [], true, true);

        var expected = $"" +
                       $" -con \"{CmdArgsTestData.TcCon}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon2}\"" +
                       $" -file \"redneck_tc.zip\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Redneck\\redneck-tc\"" +
                       $" -def \"{CmdArgsTestData.TcDef}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef2}\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Redneck"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Redneck/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Slave (Exhumed).
    /// </summary>
    [Fact]
    public void SlaveTest()
    {
        var mods = _slaveMods.MinimalMods;

        Raze raze = new();

        raze.BeforeStart(_slaveGame, _slaveCamp);
        var args = raze.GetStartGameArgs(_slaveGame, _slaveCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Slave\\slave\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Slave"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Slave/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Slave TC folder.
    /// </summary>
    [Fact]
    public void SlaveTCFolderTest()
    {
        var folderPath = Path.Combine("D:", "Games", "Slave", "slave_tc_folder");

        var slaveTcFolder = CampaignTestFactory.CreateGenericCampaign(
            "slave-tc-folder",
            GameEnum.Slave,
            new AddonFilePathWrapper(folderPath, "addon.json"));

        Raze raze = new();

        raze.BeforeStart(_slaveGame, slaveTcFolder);
        var args = raze.GetStartGameArgs(_slaveGame, slaveTcFolder, [], [], true, true);

        var expected = $"" +
                       $" -file \"{folderPath}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Slave\\slave-tc-folder\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Slave"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Slave/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Slave total conversion.
    /// </summary>
    [Fact]
    public void SlaveTcTest()
    {
        Raze raze = new();

        var zipFilePath = Path.Combine("D:", "Games", "Slave", "slave_tc.zip");

        var slaveTc = CampaignTestFactory.CreateGenericCampaign(
            "slave-tc",
            GameEnum.Slave,
            new AddonFilePathWrapper(zipFilePath, "addon.json"));

        raze.BeforeStart(_slaveGame, slaveTc);
        var args = raze.GetStartGameArgs(_slaveGame, slaveTc, [], [], true, true);

        var expected = $"" +
                       $" -file \"slave_tc.zip\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Slave\\slave-tc\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Slave"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Slave/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Shadow Warrior.
    /// </summary>
    [Fact]
    public void WangTest()
    {
        var mods = _wangMods.StandardMods;

        Raze raze = new();

        raze.BeforeStart(_wangGame, _wangCamp);
        var args = raze.GetStartGameArgs(_wangGame, _wangCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -file \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.FeatureMod}\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Wang\\wang\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Wang"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Wang/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for Twin Dragon.
    /// </summary>
    [Fact]
    public void WangTdTest()
    {
        var mods = _wangMods.AddonMods;

        Raze raze = new();

        raze.BeforeStart(_wangGame, _wangTdCamp);
        var args = raze.GetStartGameArgs(_wangGame, _wangTdCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -file \"{CmdArgsTestData.ModRequiresAddon}\"" +
                       " -file \"TD.zip\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Wang\\twindragon\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Wang"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Wang/Mods", $"{Path.Combine(Directory.GetCurrentDirectory(), "Data", "Addons", "Wang", "Campaigns")}"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Wang TC in an unpacked folder.
    /// </summary>
    [Fact]
    public void WangTCFolderTest()
    {
        Raze raze = new();

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Addons", "Wang", "Campaigns", "wang_tc_folder");

        var wangTcFolder = CampaignTestFactory.CreateGenericCampaign(
            "wang-tc-folder",
            GameEnum.Wang,
            new AddonFilePathWrapper(folderPath, "addon.json"));

        raze.BeforeStart(_wangGame, wangTcFolder);
        var args = raze.GetStartGameArgs(_wangGame, wangTcFolder, [], [], true, true);

        var expected = "" +
                       $" -file \"{folderPath}\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Wang\\wang-tc-folder\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Wang"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Wang/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a Wang loose map.
    /// </summary>
    [Fact]
    public void WangLooseMapTest()
    {
        var mods = _wangMods.StandardMods;

        Raze raze = new();

        raze.BeforeStart(_wangGame, _wangLooseMap);
        var args = raze.GetStartGameArgs(_wangGame, _wangLooseMap, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -file \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -file \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.DependentMod}\"" +
                       $" -file \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -file \"{CmdArgsTestData.FeatureMod}\"" +
                       $" -file \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Wang\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\Wang\\loose-map\"" +
                       $" -def \"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/Wang"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/Wang/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for WW2 GI.
    /// </summary>
    [Fact]
    public void WW2GITest()
    {
        var mods = _ww2Mods.MinimalMods;

        Raze raze = new();

        raze.BeforeStart(_ww2Game, _ww2Camp);
        var args = raze.GetStartGameArgs(_ww2Game, _ww2Camp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       " -ww2gi" +
                       " -file WW2GI.GRP" +
                       " -con GAME.CON" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\WW2GI\\ww2gi\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/WW2GI"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/WW2GI/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for a WW2 GI total conversion.
    /// </summary>
    [Fact]
    public void WW2GiTcTest()
    {
        Raze raze = new();

        var zipFilePath = Path.Combine("D:", "Games", "WW2GI", "ww2gi_tc.zip");

        var ww2GiTc = CampaignTestFactory.CreateDukeCampaign(
            "ww2gi-tc",
            GameEnum.WW2GI,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        raze.BeforeStart(_ww2Game, ww2GiTc);
        var args = raze.GetStartGameArgs(_ww2Game, ww2GiTc, [], [], true, true);

        var expected = "" +
                       " -ww2gi" +
                       " -file WW2GI.GRP" +
                       $" -con \"{CmdArgsTestData.TcCon}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon1}\"" +
                       $" -addcon \"{CmdArgsTestData.TcCon2}\"" +
                       $" -file \"ww2gi_tc.zip\"" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\WW2GI\\ww2gi-tc\"" +
                       $" -def \"{CmdArgsTestData.TcDef}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.TcDef2}\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/WW2GI"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/WW2GI/Mods"]);
    }

    /// <summary>
    ///     Tests that Raze generates correct start arguments for WW2 GI Platoon.
    /// </summary>
    [Fact]
    public void WW2GIPlatoonTest()
    {
        var mods = _ww2Mods.MinimalMods;

        Raze raze = new();

        raze.BeforeStart(_ww2Game, _ww2PlatoonCamp);
        var args = raze.GetStartGameArgs(_ww2Game, _ww2PlatoonCamp, mods, [], true, true);

        var expected = $"" +
                       $" -file \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -adddef \"{CmdArgsTestData.EnabledDef2}\"" +
                       " -ww2gi" +
                       " -file WW2GI.GRP" +
                       " -file PLATOONL.DAT" +
                       " -con PLATOONL.DEF" +
                       " -quick" +
                       " -nosetup" +
                       $" -savedir \"{Directory.GetCurrentDirectory()}\\Data\\Saves\\Raze\\WW2GI\\platoon\"" +
                       " -def \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);

        AssertRazeConfig(["D:/Games/WW2GI"], [$"{Directory.GetCurrentDirectory()}/Data/Addons/WW2GI/Mods"]);
    }

    /// <summary> Builds the expected Duke3D game and addon search directories from the test data layout. </summary>
    private static string[] RazeDukePaths()
    {
        var testDir = Path.Combine(Directory.GetCurrentDirectory(), "Data", "TestSetups", "Duke3D");

        return
        [
            testDir,
            Path.Combine(testDir, "addons", "vacation"),
            Path.Combine(testDir, "AddOns"),
            Path.Combine(testDir, "addons", "nw")
        ];
    }

    /// <summary>
    ///     Asserts that the Raze portable config file contains the expected game and file search directories.
    /// </summary>
    /// <param name="gameDirs">
    ///     Expected paths under the <c>[GameSearch.Directories]</c> section.
    /// </param>
    /// <param name="fileDirs">
    ///     Expected paths under the <c>[FileSearch.Directories]</c> section.
    /// </param>
    private static void AssertRazeConfig(string[] gameDirs, string[] fileDirs)
    {
        var configPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Ports", "Raze", "raze_portable.ini");
        var config = File.ReadAllText(configPath);

        var games = string.Join(Environment.NewLine, gameDirs.Select(p => $"Path={p}"));
        var files = string.Join(Environment.NewLine, fileDirs.Select(p => $"Path={p}"));

        var expected = $"""
            [GameSearch.Directories]
            {games}

            [FileSearch.Directories]
            {files}

            [SoundfontSearch.Directories]
            """.Replace('\\', '/').Replace("\r\n", "\n");

        Assert.StartsWith(expected, config.Replace("\r\n", "\n"), StringComparison.Ordinal);
    }
}
