using Addons.Addons;
using Core.All.Enums;
using Core.All.Enums.Addons;
using Core.Client.Helpers;
using Games.Games;
using Ports.Ports.EDuke32;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Disables parallelization for tests that write to the shared Rednukem install folder.
/// </summary>
[CollectionDefinition(NoParallelizationName, DisableParallelization = true)]
public sealed class RednukemNoParallelizationCollection
{
    internal const string NoParallelizationName = "Rednukem-NoParallelization";
}

/// <summary>
///     Tests for command-line arguments generated by the <see cref="Rednukem" /> port.
/// </summary>
[Collection(RednukemNoParallelizationCollection.NoParallelizationName)]
public sealed class RednukemCmdArgumentsTests
{
    private readonly DukeCampaign _duke64Camp;
    private readonly DukeCampaign _dukeCamp;
    private readonly DukeGame _dukeGame;
    private readonly LooseMap _dukeLooseMap;
    private readonly AutoloadModsTestSetups _dukeMods;
    private readonly DukeCampaign _dukeTcForVaca;
    private readonly DukeCampaign _dukeVaca;
    private readonly DukeCampaign _namCamp;

    private readonly NamGame _namGame;
    private readonly AutoloadModsTestSetups _namMods;
    private readonly DukeCampaign _redneckAgainCamp;
    private readonly DukeCampaign _redneckCamp;

    private readonly RedneckGame _redneckGame;
    private readonly AutoloadModsTestSetups _redneckMods;

    /// <summary>
    ///     Initializes a new instance of the <see cref="RednukemCmdArgumentsTests" /> class.
    /// </summary>
    public RednukemCmdArgumentsTests()
    {
        (_dukeGame, _dukeCamp, _dukeVaca, _dukeTcForVaca, _, _duke64Camp, _, _, _, _dukeLooseMap, _dukeMods) = PortTestSetups.Duke3D();
        (_namGame, _namCamp, _namMods) = PortTestSetups.Nam();
        (_redneckGame, _redneckCamp, _redneckAgainCamp, _, _redneckMods) = PortTestSetups.Redneck();
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for Duke64.
    /// </summary>
    [Fact]
    public void Duke64Test()
    {
        Rednukem rednukem = new();

        var args = rednukem.GetStartGameArgs(_dukeGame, _duke64Camp, [], [], true, true);

        var expected = "" +
                       " -j \"D:\\Games\\Duke64\"" +
                       " -gamegrp \"rom.z64\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for Duke Nukem 3D.
    /// </summary>
    [Fact]
    public void DukeTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        Rednukem rednukem = new();

        var args = rednukem.GetStartGameArgs(_dukeGame, _dukeCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for Duke Caribbean (Vacation).
    /// </summary>
    [Fact]
    public void DukeVacaTest()
    {
        var mods = _dukeMods.AddonModsWithCons;

        Rednukem eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeVaca, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModRequiresAddon}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{_dukeGame.AddonsFolders[DukeAddonEnum.DukeVaca]}\"" +
                       " -g VACATION.GRP" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\""
            ;

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for a Duke total conversion.
    /// </summary>
    [Fact]
    public void DukeTCTest()
    {
        Rednukem eduke32 = new();

        var args = eduke32.GetStartGameArgs(_dukeGame, _dukeTcForVaca, [], [], true, true);

        var expected = $"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{_dukeGame.AddonsFolders[DukeAddonEnum.DukeVaca]}\"" +
                       " -g VACATION.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       $" -j \"{Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns")}\"" +
                       " -g \"duke_tc.zip\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for a Duke TC in an unpacked folder.
    /// </summary>
    [Fact]
    public void DukeTCFolderTest()
    {
        Rednukem rednukem = new();

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns", "duke_tc_folder");

        var tcFolder = CampaignTestFactory.CreateDukeCampaign(
            "duke-tc-folder",
            GameEnum.Duke3D,
            new AddonFilePathWrapper(folderPath, "addon.json"),
            dependentAddons: new Dictionary<string, string?>
            {
                {
                    nameof(DukeAddonEnum.DukeVaca), null
                }
            },
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        var args = rednukem.GetStartGameArgs(_dukeGame, tcFolder, [], [], true, true);

        var expected = $"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{_dukeGame.AddonsFolders[DukeAddonEnum.DukeVaca]}\"" +
                       " -g VACATION.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       $" -game_dir \"{folderPath}\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for a Duke TC with an executable override.
    /// </summary>
    [Fact]
    public void DukeTCExeOverrideTest()
    {
        Rednukem rednukem = new();

        var zipFilePath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Duke3D", "Campaigns", "duke_tc.zip");

        var tcExe = CampaignTestFactory.CreateDukeCampaign(
            "duke-tc-exe",
            GameEnum.Duke3D,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            dependentAddons: new Dictionary<string, string?>
            {
                {
                    nameof(DukeAddonEnum.DukeVaca), null
                }
            },
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"],
            executables: new Dictionary<OSEnum, Dictionary<PortEnum, string>>
            {
                {
                    OSEnum.Windows, new Dictionary<PortEnum, string>
                    {
                        {
                            PortEnum.Rednukem, "rednukem.exe"
                        }
                    }
                }
            });

        var args = rednukem.GetStartGameArgs(_dukeGame, tcExe, [], [], true, true);

        var expected = $"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{_dukeGame.AddonsFolders[DukeAddonEnum.DukeVaca]}\"" +
                       " -g VACATION.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for a packed addon.
    /// </summary>
    [Fact]
    public void DukePackedAddonTest()
    {
        Rednukem rednukem = new();

        var packedCamp = PortTestSetups.PackedDukeAddonCampaign();
        var folderPath = packedCamp.FileInfo.Value.PathToFolder;
        var fileName = packedCamp.FileInfo.Value.FileName;

        var args = rednukem.GetStartGameArgs(_dukeGame, packedCamp, [], [], true, true);

        var expected = $"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{folderPath}\"" +
                       $" -g \"{fileName}\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for a Duke loose map.
    /// </summary>
    [Fact]
    public void DukeLooseMapTest()
    {
        var mods = _dukeMods.StandardModsWithCons;

        Rednukem rednukem = new();

        var args = rednukem.GetStartGameArgs(_dukeGame, _dukeLooseMap, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon1}\"" +
                       $" -mx \"{CmdArgsTestData.EnabledCon2}\"" +
                       $" -g \"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g \"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g \"{CmdArgsTestData.DependentMod}\"" +
                       $" -g \"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Mods\"" +
                       $" -j \"{_dukeGame.GameInstallFolder}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Duke3D\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for NAM.
    /// </summary>
    [Fact]
    public void NamTest()
    {
        var mods = _namMods.MinimalMods;

        Rednukem rednukem = new();

        var args = rednukem.GetStartGameArgs(_namGame, _namCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\NAM\\Mods\"" +
                       " -j \"D:\\Games\\NAM\"" +
                       " -nam" +
                       " -gamegrp NAM.GRP" +
                       " -x GAME.CON" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for a NAM total conversion.
    /// </summary>
    [Fact]
    public void NamTcTest()
    {
        Rednukem rednukem = new();

        var zipFilePath = Path.Combine("D:", "Games", "NAM", "nam_tc.zip");
        var folderPath = Path.GetDirectoryName(zipFilePath);

        var namTc = CampaignTestFactory.CreateDukeCampaign(
            "nam-tc",
            GameEnum.NAM,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            mainCon: "TC.CON",
            additionalCons: ["TC1.CON", "TC2.CON"],
            mainDef: "TC.DEF",
            additionalDefs: ["TC1.DEF", "TC2.DEF"]);

        var args = rednukem.GetStartGameArgs(_namGame, namTc, [], [], true, true);

        var expected = $"" +
                       " -j \"D:\\Games\\NAM\"" +
                       " -nam" +
                       " -gamegrp NAM.GRP" +
                       $" -x \"{CmdArgsTestData.TcCon}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon1}\"" +
                       $" -mx \"{CmdArgsTestData.TcCon2}\"" +
                       $" -j \"{folderPath}\"" +
                       " -g \"nam_tc.zip\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       $" -h \"{CmdArgsTestData.TcDef}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef1}\"" +
                       $" -mh \"{CmdArgsTestData.TcDef2}\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for Redneck Rampage.
    /// </summary>
    [Fact]
    public void RedneckTest()
    {
        var mods = _redneckMods.MinimalMods;

        Rednukem rednukem = new();

        var args = rednukem.GetStartGameArgs(_redneckGame, _redneckCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Redneck\\Mods\"" +
                       " -j \"D:\\Games\\Redneck\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that Rednukem generates correct start arguments for Redneck Rampage Rides Again.
    /// </summary>
    [Fact]
    public void RedneckAgainTest()
    {
        var mods = _redneckMods.MinimalMods;

        Rednukem rednukem = new();

        var args = rednukem.GetStartGameArgs(_redneckGame, _redneckAgainCamp, mods, [], true, true);

        var expected = $"" +
                       $" -g \"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh \"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -j \"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Redneck\\Mods\"" +
                       " -j \"D:\\Games\\Again\"" +
                       " -quick" +
                       " -d blank.edm" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h \"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    private static readonly string[] BlankAnmFiles =
    [
        "LOGO.ANM",
        "XATLOGO.ANM",
        "REDNECK.ANM",
        "RR_INTRO.ANM",
        "REDINT.MVE"
    ];

    /// <summary>
    ///     Deletes the blank animation files from the Rednukem install folder.
    /// </summary>
    private static void DeleteBlankAnmFiles(string installFolder)
    {
        foreach (var file in BlankAnmFiles)
        {
            var path = Path.Combine(installFolder, file);

            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
    }

    /// <summary>
    ///     Tests that skipping the intro creates the blank animation files and appends the blank demo parameter.
    /// </summary>
    [Fact]
    public void SkipIntro_CreatesBlankAnmFiles()
    {
        Rednukem rednukem = new();

        var installFolder = Path.Combine(ClientProperties.PortsFolderPath, rednukem.ShortName);
        Directory.CreateDirectory(installFolder);
        DeleteBlankAnmFiles(installFolder);

        try
        {
            var args = rednukem.GetStartGameArgs(_dukeGame, _dukeCamp, [], [], skipIntro: true, skipStartup: true);

            Assert.Contains(" -quick", args);
            Assert.Contains(" -d blank.edm", args);

            foreach (var file in BlankAnmFiles)
            {
                Assert.True(File.Exists(Path.Combine(installFolder, file)), $"Expected blank intro file '{file}' to be created.");
            }
        }
        finally
        {
            DeleteBlankAnmFiles(installFolder);
        }
    }

    /// <summary>
    ///     Tests that not skipping the intro does not create the blank animation files.
    /// </summary>
    [Fact]
    public void SkipIntroFalse_DoesNotCreateBlankAnmFiles()
    {
        Rednukem rednukem = new();

        var installFolder = Path.Combine(ClientProperties.PortsFolderPath, rednukem.ShortName);
        Directory.CreateDirectory(installFolder);
        DeleteBlankAnmFiles(installFolder);

        try
        {
            _ = rednukem.GetStartGameArgs(_dukeGame, _dukeCamp, [], [], skipIntro: false, skipStartup: true);

            foreach (var file in BlankAnmFiles)
            {
                Assert.False(File.Exists(Path.Combine(installFolder, file)), $"Expected blank intro file '{file}' to remain absent.");
            }
        }
        finally
        {
            DeleteBlankAnmFiles(installFolder);
        }
    }
}
