using Addons.Addons;
using Core.All.Enums;
using Core.Client.Helpers;
using Games.Games;
using Ports.Ports.EDuke32;
using Tests.Unit.Helpers;

namespace Tests.Unit.CmdArguments;

/// <summary>
///     Tests for command-line arguments generated by the <see cref="VoidSW" /> port.
/// </summary>
public sealed class VoidSWCmdArgumentsTests
{
    /// <summary>
    ///     Shadow Warrior base campaign.
    /// </summary>
    private readonly GenericCampaign _wangCamp;

    /// <summary>
    ///     Shadow Warrior game instance.
    /// </summary>
    private readonly WangGame _wangGame;

    /// <summary>
    ///     Shadow Warrior loose map.
    /// </summary>
    private readonly LooseMap _wangLooseMap;

    /// <summary>
    ///     Shadow Warrior mods test setups.
    /// </summary>
    private readonly AutoloadModsTestSetups _wangMods;

    /// <summary>
    ///     Twin Dragon campaign.
    /// </summary>
    private readonly GenericCampaign _wangTdCamp;

    /// <summary>
    ///     Initializes a new instance of the <see cref="VoidSWCmdArgumentsTests" /> class.
    /// </summary>
    public VoidSWCmdArgumentsTests()
    {
        (_wangGame, _wangCamp, _wangTdCamp, _wangLooseMap, _wangMods) = PortTestSetups.Wang();
    }

    /// <summary>
    ///     Tests that VoidSW generates correct start arguments for Shadow Warrior.
    /// </summary>
    [Fact]
    public void WangTest()
    {
        var mods = _wangMods.StandardMods;

        VoidSW voidSw = new();

        var args = voidSw.GetStartGameArgs(_wangGame, _wangCamp, mods, [], true, true, 3);

        var expected = $"" +
                       $" -g\"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh\"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh\"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -g\"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g\"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g\"{CmdArgsTestData.DependentMod}\"" +
                       $" -g\"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g\"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j\"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Wang\\Mods\"" +
                       " -j\"D:\\Games\\Wang\"" +
                       " -addon0" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h\"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that VoidSW generates correct start arguments for Twin Dragon.
    /// </summary>
    [Fact]
    public void WangTdTest()
    {
        var mods = _wangMods.AddonMods;

        VoidSW voidSw = new();

        var args = voidSw.GetStartGameArgs(_wangGame, _wangTdCamp, mods, [], true, true, 3);

        var expected = $"" +
                       $" -g\"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh\"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh\"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -g\"{CmdArgsTestData.ModRequiresAddon}\"" +
                       $" -j\"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Wang\\Mods\"" +
                       " -j\"D:\\Games\\Wang\"" +
                       " -addon0" +
                       $" -j\"{Path.Combine(Directory.GetCurrentDirectory(), "Data", "Addons", "Wang", "Campaigns")}\"" +
                       " -g\"TD.zip\"" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h\"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that VoidSW generates correct start arguments for a Wang TC in an unpacked folder.
    /// </summary>
    [Fact]
    public void WangTCFolderTest()
    {
        VoidSW voidSw = new();

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Addons", "Wang", "Campaigns", "wang_tc_folder");

        var wangTcFolder = CampaignTestFactory.CreateGenericCampaign(
            "wang-tc-folder",
            GameEnum.Wang,
            new AddonFilePathWrapper(folderPath, "addon.json"));

        var args = voidSw.GetStartGameArgs(_wangGame, wangTcFolder, [], [], true, true, 3);

        var expected = $"" +
                       $" -j\"D:\\Games\\Wang\"" +
                       " -addon0" +
                       $" -game_dir \"{folderPath}\"" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h\"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that VoidSW generates correct start arguments for a Wang total conversion.
    /// </summary>
    [Fact]
    public void WangTcTest()
    {
        VoidSW voidSw = new();

        var zipFilePath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Addons", "Wang", "Campaigns", "wang_tc.zip");
        var folderPath = Path.GetDirectoryName(zipFilePath);

        var wangTc = CampaignTestFactory.CreateGenericCampaign(
            "wang-tc",
            GameEnum.Wang,
            new AddonFilePathWrapper(zipFilePath, "addon.json"));

        var args = voidSw.GetStartGameArgs(_wangGame, wangTc, [], [], true, true, 3);

        var expected = $"" +
                       $" -j\"D:\\Games\\Wang\"" +
                       " -addon0" +
                       $" -j\"{folderPath}\"" +
                       $" -g\"wang_tc.zip\"" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h\"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that VoidSW generates correct start arguments for a Wang TC with an executable override.
    /// </summary>
    [Fact]
    public void WangTCExeOverrideTest()
    {
        VoidSW voidSw = new();

        var zipFilePath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Addons", "Wang", "Campaigns", "wang_tc.zip");

        var wangTcExe = CampaignTestFactory.CreateGenericCampaign(
            "wang-tc-exe",
            GameEnum.Wang,
            new AddonFilePathWrapper(zipFilePath, "addon.json"),
            executables: new Dictionary<OSEnum, Dictionary<PortEnum, string>>
            {
                {
                    OSEnum.Windows, new Dictionary<PortEnum, string>
                    {
                        {
                            PortEnum.VoidSW, "voidsw.exe"
                        }
                    }
                }
            });

        var args = voidSw.GetStartGameArgs(_wangGame, wangTcExe, [], [], true, true, 3);

        var expected = $"" +
                       $" -j\"D:\\Games\\Wang\"" +
                       " -addon0" +
                       " -s3" +
                       " -quick" +
                       " -nosetup" +
                       " -usecwd" +
                       " -h\"a\"" +
                       "";

        CmdArgsAssert.Equal(expected, args);
    }

    /// <summary>
    ///     Tests that VoidSW generates correct start arguments for a Wang loose map.
    /// </summary>
    [Fact]
    public void WangLooseMapTest()
    {
        var mods = _wangMods.StandardMods;

        VoidSW voidSw = new();

        var args = voidSw.GetStartGameArgs(_wangGame, _wangLooseMap, mods, [], true, true, 3);

        var expected = $"" +
                       $" -g\"{CmdArgsTestData.EnabledMod}\"" +
                       $" -mh\"{CmdArgsTestData.EnabledDef1}\"" +
                       $" -mh\"{CmdArgsTestData.EnabledDef2}\"" +
                       $" -g\"{CmdArgsTestData.ModIncompatibleWithAddon}\"" +
                       $" -g\"{CmdArgsTestData.IncompatibleModWithCompatibleVersion}\"" +
                       $" -g\"{CmdArgsTestData.DependentMod}\"" +
                       $" -g\"{CmdArgsTestData.DependentModWithCompatibleVersion}\"" +
                       $" -g\"{CmdArgsTestData.FeatureMod}\"" +
                       $" -j\"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Wang\\Mods\"" +
                       $" -j\"D:\\Games\\Wang\"" +
                       $" -j\"{Directory.GetCurrentDirectory()}\\Data\\Addons\\Wang\\Maps\"" +
                       $" -map \"{CmdArgsTestData.LooseMap}\"" +
                       $" -s3" +
                       $" -quick" +
                       $" -nosetup" +
                       $" -usecwd" +
                       $" -h\"a\"" +
                       $"";

        CmdArgsAssert.Equal(expected, args);
    }
}
