// <auto-generated />
using System;
using ClientCommon.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientCommon.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240617165320_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ClientCommon.Config.DbEntities.DisabledDbEntity", b =>
                {
                    b.Property<string>("AddonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("addon_id");

                    b.HasKey("AddonId");

                    b.ToTable("disabled_addons", "main");
                });

            modelBuilder.Entity("ClientCommon.Config.DbEntities.GamePathsDbEntity", b =>
                {
                    b.Property<string>("Game")
                        .HasColumnType("TEXT")
                        .HasColumnName("game");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("Game");

                    b.ToTable("game_paths", "main");
                });

            modelBuilder.Entity("ClientCommon.Config.DbEntities.PlaytimesDbEntity", b =>
                {
                    b.Property<string>("AddonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("addon_id");

                    b.Property<TimeSpan>("Playtime")
                        .HasColumnType("TEXT")
                        .HasColumnName("playtime");

                    b.HasKey("AddonId");

                    b.ToTable("playtimes", "main");
                });

            modelBuilder.Entity("ClientCommon.Config.DbEntities.ScoresDbEntity", b =>
                {
                    b.Property<string>("AddonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("addon_id");

                    b.Property<bool>("IsUpvoted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_upvoted");

                    b.HasKey("AddonId");

                    b.ToTable("scores", "main");
                });

            modelBuilder.Entity("ClientCommon.Config.DbEntities.SettingsDbEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("settings", "main");
                });
#pragma warning restore 612, 618
        }
    }
}
