name: Build and test
on:
  push:

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Unit
      run: dotnet test ./src/Tests.Unit/Tests.Unit.csproj --no-build --verbosity normal
    - name: Test External
      run: dotnet test ./src/Tests.External/Tests.External.csproj --no-build --verbosity normal
      
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Unit
      run: dotnet test ./src/Tests.Unit/Tests.Unit.csproj --no-build --verbosity normal
    - name: Test External
      run: dotnet test ./src/Tests.External/Tests.External.csproj --no-build --verbosity normal
